baseURL = "https://mtf.wiki"
title = "MtF Wiki"
theme = "zdoc"

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

copyright = "&copy; 2020-{year} MtF Wiki. All Rights Reserved"
timeout = "1M"
enableEmoji = true
enableRobotsTXT = true
paginate = 13
rssLimit = 100

googleAnalytics = ""

disableKinds = ["taxonomyTerm"]

[params]
hostName = "https://mtf.wiki"
custom_css = [
  "customize.scss"
]
custom_js = [
  "qrcode.min.js",
  "customize.js"
]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  tag = "tags"
