[[main]]
  identifier = "docs"
  name = "文档"
  url = "docs"
  weight = 1

[[main]]
  identifier = "conv"
  name = "激素换算"
  url = "converter"
  weight = 2

[[main]]
  identifier = "cupc"
  name = "胸围计算"
  url = "cup-calculator"
  weight = 3

[[main]]
  identifier = "about"
  name = "关于我们"
  url = "about"
  weight = 4

#[[main]]
#  identifier = "updates"
#  name = "Updates"
#  url = "updates"
#  weight = 2
#
#[[main]]
#  identifier = "blog"
#  name = "Blog"
#  url = "blog"
#  weight = 3
