[[main]]
  identifier = "docs"
  name = "資料"
  url = "docs"
  weight = 1

[[main]]
  identifier = "about"
  name = "MtF.wiki について"
  url = "about"
  weight = 4

#[[main]]
#  identifier = "updates"
#  name = "Updates"
#  url = "updates"
#  weight = 2
#
#[[main]]
#  identifier = "blog"
#  name = "Blog"
#  url = "blog"
#  weight = 3
