# see https://github.com/actions/labeler

Content | 内容:
  - '**/docs/**'

HRT:
  - '**/docs/hrt/*'
  - '**/docs/medicine/*'

SRS:
  - '**/docs/srs/*'

FFS:
  - '**/docs/ffs/*'

Psycho | 精神科:
  - '**/docs/psyco/*'
  - '**/docs/psycho/*'

Site | 站点:
  - '**/themes/**'

Voice | 声音相关:
  - '**/docs/docs/vocal-surgery/**'
  - '**/docs/docs/vocal-therapy/**'
