name: Test Site

on:
  pull_request:
    paths-ignore:
      - .github
      - README.md
      - LICENSE

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Generated Cache
        uses: actions/cache@v3
        with:
          path: resources/_gen
          key: ${{ runner.os }}-generated-${{ hashFiles('**') }}
          restore-keys: ${{ runner.os }}-generated
      - name: Build
        run: hugo --minify
