name: Test Site

on:
  pull_request:
    paths-ignore:
      - '.github'
      - 'README.md'
      - 'LICENSE'

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - run: npx markdownlint-cli .
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Hugo Cache
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-hugomod-
      - name: Build
        run: hugo --minify
